#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Component, Path, PathBuf};
use std::time::UNIX_EPOCH;

// ---------------- Types ----------------

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct NoteMeta {
    path: String, // relative to notes root, forward slashes, e.g. "work/idea.md"
    folder: String, // "" for root
    title: String,
    tags: Vec<String>,
    snippet: String,
    mtime: i64, // unix seconds
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct SearchHit {
    meta: NoteMeta,
    snippet: String, // plain text around the first match
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct NoteContent {
    tags: Vec<String>,
    body: String,
    mtime: i64,
}

#[derive(Deserialize)]
struct SaveNoteArgs {
    tags: Vec<String>,
    body: String,
}

// ---------------- Path safety ----------------

/// `fs::canonicalize` on Windows returns `\\?\`-prefixed (extended-length)
/// paths. Strip that prefix so the path stays comparable with normal
/// (root-relative) paths and `Path::strip_prefix` keeps working.
fn strip_extended_prefix(p: &Path) -> PathBuf {
    let s = p.to_string_lossy();
    if let Some(stripped) = s.strip_prefix(r"\\?\") {
        Path::new(stripped).to_path_buf()
    } else {
        p.to_path_buf()
    }
}

/// Join a relative path to the notes root and verify the result stays inside it.
fn resolve_in_root(root: &Path, rel: &str) -> Result<PathBuf, String> {
    if rel.trim().is_empty() {
        return Err("empty path".into());
    }
    let rel_path = Path::new(rel);
    if rel_path.is_absolute() {
        return Err("absolute path not allowed".into());
    }
    let mut inside = root.to_path_buf();
    for comp in rel_path.components() {
        match comp {
            Component::Normal(c) => inside.push(c),
            Component::CurDir => {}
            // Note paths are generated by our own scan and never contain `..`;
            // reject them outright instead of resolving them.
            Component::ParentDir => return Err("path escapes notes root".into()),
            _ => return Err("invalid path".into()),
        }
    }
    if inside.exists() {
        let canon = fs::canonicalize(&inside).map_err(|e| e.to_string())?;
        let canon_root = fs::canonicalize(root).map_err(|e| e.to_string())?;
        if !canon.starts_with(&canon_root) {
            return Err("path escapes notes root".into());
        }
        // Drop the `\\?\` prefix so results compare cleanly with the raw
        // root elsewhere (e.g. in read_meta's strip_prefix).
        return Ok(strip_extended_prefix(&canon));
    }
    Ok(inside)
}

// ---------------- Front matter ----------------

/// Parse an optional front matter block: first line `---`, closed by `---`/`...`.
/// Supports `tags: a, b` and YAML-style `- item` lists. Returns (tags, body).
fn parse_frontmatter(text: &str) -> (Vec<String>, String) {
    let mut lines = text.lines();
    let Some(first) = lines.next() else {
        return (Vec::new(), text.to_string());
    };
    if first.trim_end() != "---" {
        return (Vec::new(), text.to_string());
    }
    let rest: Vec<&str> = lines.collect();
    let Some(end_idx) = rest
        .iter()
        .position(|l| l.trim_end() == "---" || l.trim_end() == "...")
    else {
        return (Vec::new(), text.to_string());
    };
    let block = &rest[..end_idx];

    let mut tags: Vec<String> = Vec::new();
    let mut i = 0;
    while i < block.len() {
        let trimmed = block[i].trim();
        if let Some(rest_part) = trimmed.strip_prefix("tags:") {
            let inline = rest_part.trim().trim_matches(|c| c == '[' || c == ']').trim();
            if !inline.is_empty() {
                for part in inline.split(',') {
                    let t = part.trim().trim_matches(|c| c == '"' || c == '\'');
                    if !t.is_empty() {
                        tags.push(t.to_string());
                    }
                }
            } else {
                let mut j = i + 1;
                while j < block.len() {
                    let l = block[j].trim();
                    if let Some(item) = l.strip_prefix("- ") {
                        let t = item.trim().trim_matches(|c| c == '"' || c == '\'');
                        if !t.is_empty() {
                            tags.push(t.to_string());
                        }
                        j += 1;
                    } else if l.is_empty() {
                        j += 1;
                    } else {
                        break;
                    }
                }
                i = j;
                continue;
            }
        }
        i += 1;
    }
    tags.retain(|t| !t.is_empty());

    let body: String = rest[end_idx + 1..].join("\n");
    (
        tags,
        body.trim_start_matches('\n')
            .trim_start_matches('\r')
            .to_string(),
    )
}

fn render_frontmatter(tags: &[String], body: &str) -> String {
    if tags.is_empty() {
        return body.to_string();
    }
    let mut out = String::from("---\ntags: ");
    out.push_str(&tags.join(", "));
    out.push_str("\n---\n\n");
    out.push_str(body);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

// ---------------- Text helpers ----------------

fn heading_text(line: &str) -> Option<String> {
    let t = line.trim_start();
    let hashes = t.chars().take_while(|c| *c == '#').count();
    if !(1..=6).contains(&hashes) {
        return None;
    }
    let rest = t[hashes..].trim();
    if rest.is_empty() {
        return None;
    }
    let cleaned = rest.trim_end_matches('#').trim().to_string();
    if cleaned.is_empty() {
        None
    } else {
        Some(cleaned)
    }
}

fn extract_title(body: &str, fallback: &str) -> String {
    for line in body.lines() {
        if let Some(t) = heading_text(line) {
            return t;
        }
    }
    fallback.to_string()
}

/// Remove inline markdown markers for a plain-text snippet.
fn strip_inline(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    let mut in_code = false;
    let mut link_text: Option<String> = None;
    while let Some(c) = chars.next() {
        if let Some(t) = link_text.as_mut() {
            if c == ']' {
                out.push_str(t);
                link_text = None;
                if chars.peek() == Some(&'(') {
                    chars.next();
                    let mut depth = 1u32;
                    for nc in chars.by_ref() {
                        if nc == '(' {
                            depth += 1;
                        } else if nc == ')' {
                            depth -= 1;
                            if depth == 0 {
                                break;
                            }
                        }
                    }
                }
            } else {
                t.push(c);
            }
            continue;
        }
        match c {
            '`' => in_code = !in_code,
            '!' => {
                // image: swallow the alt text too
                if chars.peek() == Some(&'[') {
                    chars.next();
                    link_text = Some(String::new());
                }
            }
            '[' => link_text = Some(String::new()),
            c if !in_code && matches!(c, '*' | '_' | '~' | '>' | '#' | '|') => {}
            c => out.push(c),
        }
    }
    out
}

/// First few lines of visible body text as a snippet (max_chars chars).
fn plain_snippet(body: &str, max_chars: usize) -> String {
    let mut out = String::new();
    let mut in_fence = false;
    for line in body.lines() {
        let t = line.trim();
        if t.starts_with("```") || t.starts_with("~~~") {
            in_fence = !in_fence;
            continue;
        }
        if in_fence || t.is_empty() {
            continue;
        }
        if heading_text(t).is_some() {
            continue;
        }
        // strip a leading list marker
        let stripped: Option<&str> = t
            .strip_prefix("- ")
            .or_else(|| t.strip_prefix("* "))
            .or_else(|| t.strip_prefix("+ "))
            .or_else(|| {
                let n = t.chars().take_while(|c| c.is_ascii_digit()).count();
                if n == 0 {
                    return None;
                }
                let rest = &t[n..];
                rest.strip_prefix(". ").or_else(|| rest.strip_prefix(") "))
            });
        let s = strip_inline(stripped.unwrap_or(t));
        if s.is_empty() {
            continue;
        }
        if !out.is_empty() {
            out.push(' ');
        }
        out.push_str(&s);
        if out.chars().count() >= max_chars {
            break;
        }
    }
    let chars: Vec<char> = out.chars().collect();
    if chars.len() > max_chars {
        chars[..max_chars].iter().collect::<String>() + "…"
    } else {
        out
    }
}

fn mtime_of(path: &Path) -> i64 {
    fs::metadata(path)
        .and_then(|m| m.modified())
        .ok()
        .and_then(|t| t.duration_since(UNIX_EPOCH).ok())
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

/// Read a note's metadata. `rel` is the note's root-relative path (as
/// listed), `full` is the absolute path of the file. Keeping them separate
/// avoids fragile `strip_prefix` comparisons between a user-typed root and
/// a canonicalized path — on Windows `fs::canonicalize` adds a `\\?\`
/// prefix, which silently broke read-back after every save.
fn read_meta(rel: &Path, full: &Path) -> Option<NoteMeta> {
    let rel_s = rel.to_string_lossy().replace('\\', "/");
    let folder = rel
        .parent()
        .map(|p| p.to_string_lossy().replace('\\', "/"))
        .unwrap_or_default();
    let text = fs::read_to_string(full).ok()?;
    let (tags, body) = parse_frontmatter(&text);
    let name = full.file_stem()?.to_string_lossy().to_string();
    let title = extract_title(&body, &name);
    let snippet = plain_snippet(&body, 100);
    Some(NoteMeta {
        path: rel_s,
        folder,
        title,
        tags,
        snippet,
        mtime: mtime_of(full),
    })
}

fn collect_notes(root: &Path) -> Result<Vec<NoteMeta>, String> {
    let mut metas: Vec<NoteMeta> = Vec::new();
    walk(root, root, &mut metas)?;
    metas.sort_by(|a, b| {
        b.mtime
            .cmp(&a.mtime)
            .then_with(|| a.title.to_lowercase().cmp(&b.title.to_lowercase()))
    });
    Ok(metas)
}

fn walk(dir: &Path, root: &Path, out: &mut Vec<NoteMeta>) -> Result<(), String> {
    let entries = fs::read_dir(dir).map_err(|e| e.to_string())?;
    for entry in entries {
        let entry = entry.map_err(|e| e.to_string())?;
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            walk(&path, root, out)?;
        } else if name.to_lowercase().ends_with(".md") {
            if let Ok(rel) = path.strip_prefix(root) {
                if let Some(meta) = read_meta(rel, &path) {
                    out.push(meta);
                }
            }
        }
    }
    Ok(())
}

fn sanitize_filename(s: &str) -> String {
    const INVALID: [char; 9] = ['<', '>', ':', '"', '|', '?', '*', '\\', '/'];
    let cleaned: String = s.chars().filter(|c| !INVALID.contains(c)).collect();
    let trimmed = cleaned.trim().trim_end_matches('.');
    if trimmed.is_empty() {
        "untitled".to_string()
    } else {
        trimmed.to_string()
    }
}

// ---------------- Commands ----------------

#[tauri::command]
fn list_notes(dir: String) -> Result<Vec<NoteMeta>, String> {
    eprintln!("[rustmd] list_notes dir={dir}");
    let res = collect_notes(Path::new(&dir));
    match &res {
        Ok(n) => eprintln!("[rustmd] list_notes ok, {} notes", n.len()),
        Err(e) => eprintln!("[rustmd] list_notes ERR: {e}"),
    }
    res
}

#[tauri::command]
fn read_note(dir: String, path: String) -> Result<NoteContent, String> {
    eprintln!("[rustmd] read_note dir={dir} path={path}");
    let res = (|| {
        let full = resolve_in_root(Path::new(&dir), &path)?;
        let text = fs::read_to_string(&full).map_err(|e| e.to_string())?;
        let (tags, body) = parse_frontmatter(&text);
        Ok(NoteContent {
            tags,
            body,
            mtime: mtime_of(&full),
        })
    })();
    if res.is_err() {
        eprintln!("[rustmd] read_note ERR: {}", res.as_ref().err().unwrap());
    }
    res
}

fn save_note_impl(root: &Path, rel: &str, tags: &[String], body: &str) -> Result<NoteMeta, String> {
    let full = resolve_in_root(root, rel)?;
    if let Some(parent) = full.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let content = render_frontmatter(tags, body);
    // Skip the write when the on-disk content is already identical. A
    // no-op write still updates the file mtime, which (a) re-sorts the
    // note list and (b) under `tauri dev` trips the file watcher,
    // restarting the app right after every open ("window closes, list
    // disappears" loop).
    let existing = fs::read_to_string(&full).ok();
    if existing.as_deref() != Some(content.as_str()) {
        fs::write(&full, content).map_err(|e| e.to_string())?;
    }
    // Re-read via the root-relative path (not strip_prefix on the
    // canonicalized path, which fails on Windows `\\?\` paths).
    read_meta(Path::new(rel), &full).ok_or_else(|| "failed to read note back".into())
}

#[tauri::command]
fn save_note(dir: String, path: String, args: SaveNoteArgs) -> Result<NoteMeta, String> {
    eprintln!(
        "[rustmd] save_note dir={dir} path={path} tags={:?} body_len={}",
        args.tags,
        args.body.len()
    );
    let res = save_note_impl(Path::new(&dir), &path, &args.tags, &args.body);
    match &res {
        Ok(_) => eprintln!("[rustmd] save_note ok"),
        Err(e) => eprintln!("[rustmd] save_note ERR: {e}"),
    }
    res
}

#[tauri::command]
fn create_note(dir: String, folder: String) -> Result<String, String> {
    let root = Path::new(&dir);
    let folder = folder.replace('\\', "/");
    let target_dir = resolve_in_root(root, if folder.is_empty() { "." } else { &folder })?;
    fs::create_dir_all(&target_dir).map_err(|e| e.to_string())?;
    let mut candidate = "untitled.md".to_string();
    let mut i = 1u32;
    while target_dir.join(&candidate).exists() {
        candidate = format!("untitled {i}.md");
        i += 1;
    }
    fs::write(target_dir.join(&candidate), "").map_err(|e| e.to_string())?;
    Ok(if folder.is_empty() {
        candidate
    } else {
        format!("{folder}/{candidate}")
    })
}

#[tauri::command]
fn rename_note(dir: String, path: String, name: String) -> Result<String, String> {
    let root = Path::new(&dir);
    let full = resolve_in_root(root, &path)?;
    let clean = sanitize_filename(&name);
    let new_name = if clean.to_lowercase().ends_with(".md") {
        clean
    } else {
        format!("{clean}.md")
    };
    let new_full = full
        .parent()
        .ok_or_else(|| "no parent dir".to_string())?
        .join(&new_name);
    fs::rename(&full, &new_full).map_err(|e| e.to_string())?;
    new_full
        .strip_prefix(root)
        .map(|p| p.to_string_lossy().replace('\\', "/"))
        .map_err(|e| e.to_string())
}

#[tauri::command]
fn delete_note(dir: String, path: String) -> Result<(), String> {
    let full = resolve_in_root(Path::new(&dir), &path)?;
    if !full.is_file() {
        return Err("not a file".into());
    }
    fs::remove_file(&full).map_err(|e| e.to_string())
}

#[tauri::command]
fn move_note(dir: String, path: String, dest_folder: String) -> Result<String, String> {
    let root = Path::new(&dir);
    let full = resolve_in_root(root, &path)?;
    let normalized = dest_folder.replace('\\', "/");
    let dest = resolve_in_root(
        root,
        if normalized.is_empty() { "." } else { &normalized },
    )?;
    fs::create_dir_all(&dest).map_err(|e| e.to_string())?;
    let file_name = full.file_name().ok_or_else(|| "no file name".to_string())?;
    let mut target = dest.join(file_name);
    if target == full {
        return full
            .strip_prefix(root)
            .map(|p| p.to_string_lossy().replace('\\', "/"))
            .map_err(|e| e.to_string());
    }
    if target.exists() {
        let stem = full
            .file_stem()
            .ok_or_else(|| "no file stem".to_string())?
            .to_string_lossy()
            .to_string();
        let mut i = 1u32;
        loop {
            let candidate = format!("{stem} ({i}).md");
            if !dest.join(&candidate).exists() {
                target = dest.join(candidate);
                break;
            }
            i += 1;
        }
    }
    fs::rename(&full, &target).map_err(|e| e.to_string())?;
    target
        .strip_prefix(root)
        .map(|p| p.to_string_lossy().replace('\\', "/"))
        .map_err(|e| e.to_string())
}

#[tauri::command]
fn search_notes(dir: String, query: String) -> Result<Vec<SearchHit>, String> {
    let root = Path::new(&dir);
    let q = query.to_lowercase();
    if q.trim().is_empty() {
        return Ok(Vec::new());
    }
    let metas = collect_notes(root)?;
    let mut hits: Vec<SearchHit> = Vec::new();
    for meta in metas {
        let Ok(full) = resolve_in_root(root, &meta.path) else {
            continue;
        };
        let Ok(text) = fs::read_to_string(&full) else {
            continue;
        };
        let (_, body) = parse_frontmatter(&text);
        let lower = body.to_lowercase();
        let Some(pos) = lower.find(&q) else {
            continue;
        };
        let mut start = pos.saturating_sub(40);
        while start > 0 && !lower.is_char_boundary(start) {
            start -= 1;
        }
        let mut end = (pos + q.len()).saturating_add(60).min(lower.len());
        while end < lower.len() && !lower.is_char_boundary(end) {
            end -= 1;
        }
        // Prefer the original casing; fall back to the lowercased window if
        // case folding changed the string length before `start`.
        let window = match body.get(start..end) {
            Some(w) if w.to_lowercase() == lower[start..end] => w.to_string(),
            _ => lower[start..end].to_string(),
        };
        let snippet = if start > 0 {
            format!("…{}", window.trim_start())
        } else {
            window.trim_start().to_string()
        };
        hits.push(SearchHit { meta, snippet });
        if hits.len() >= 500 {
            break;
        }
    }
    Ok(hits)
}

/// Write a UTF-8 file at an absolute path (used for HTML export;
/// the path comes from the user's save dialog).
#[tauri::command]
fn write_text(path: String, content: String) -> Result<(), String> {
    fs::write(Path::new(&path), content).map_err(|e| e.to_string())
}

/// Write raw bytes at an absolute path (used for PNG/PDF export;
/// the path comes from the user's save dialog).
#[tauri::command]
fn write_bytes(path: String, data: Vec<u8>) -> Result<(), String> {
    fs::write(Path::new(&path), data).map_err(|e| e.to_string())
}

fn main() {
    // Diagnostic: mark Rust panics so they are easy to find in `tauri dev` output.
    std::panic::set_hook({
        let default = std::panic::take_hook();
        Box::new(move |info| {
            eprintln!("[rustmd] === RUST PANIC ===");
            default(info);
        })
    });

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        // Diagnostic: log window close/destroy and app exit to stderr so a
        // "flashed and exited" session leaves a trace in `tauri dev` output.
        .on_window_event(|window, event| match event {
            tauri::WindowEvent::CloseRequested { .. } => {
                eprintln!("[rustmd] window {} close requested", window.label())
            }
            tauri::WindowEvent::Destroyed => {
                eprintln!("[rustmd] window {} destroyed", window.label())
            }
            _ => {}
        })
        .invoke_handler(tauri::generate_handler![
            list_notes,
            read_note,
            save_note,
            create_note,
            rename_note,
            delete_note,
            move_note,
            search_notes,
            write_text,
            write_bytes
        ])
        .build(tauri::generate_context!())
        .expect("error while running tauri application")
        .run(|_app, event| match event {
            tauri::RunEvent::Exit => eprintln!("[rustmd] run event: EXIT (last window closed)"),
            _ => {}
        });
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_frontmatter_inline_tags() {
        let (tags, body) = parse_frontmatter("---\ntags: a, b\ntitle: x\n---\n\n# Hello\n");
        assert_eq!(tags, vec!["a", "b"]);
        assert!(body.starts_with("# Hello"));
    }

    #[test]
    fn parse_frontmatter_list_tags() {
        let (tags, body) =
            parse_frontmatter("---\ntags:\n  - 工作\n  - 计划\n---\nbody\n");
        assert_eq!(tags, vec!["工作", "计划"]);
        assert_eq!(body, "body");
    }

    #[test]
    fn parse_frontmatter_absent() {
        let (tags, body) = parse_frontmatter("# Just a doc\n\nhello\n");
        assert!(tags.is_empty());
        assert_eq!(body, "# Just a doc\n\nhello\n");
    }

    #[test]
    fn parse_frontmatter_unclosed() {
        let (tags, body) = parse_frontmatter("---\ntags: a\nno closing line\n");
        assert!(tags.is_empty());
        assert_eq!(body, "---\ntags: a\nno closing line\n");
    }

    #[test]
    fn render_frontmatter_roundtrip() {
        let tags = vec!["a".to_string(), "b".to_string()];
        let content = render_frontmatter(&tags, "# Title\n\nBody\n");
        let (tags2, body2) = parse_frontmatter(&content);
        assert_eq!(tags2, tags);
        assert!(body2.starts_with("# Title"));
        assert!(body2.contains("Body"));
    }

    #[test]
    fn render_frontmatter_empty_tags() {
        let content = render_frontmatter(&[], "just body");
        assert_eq!(content, "just body");
    }

    #[test]
    fn extract_title_first_heading() {
        assert_eq!(
            extract_title("intro\n\n## The Title\n\nmore", "fallback"),
            "The Title"
        );
    }

    #[test]
    fn extract_title_fallback() {
        assert_eq!(extract_title("no headings here", "fallback"), "fallback");
    }

    #[test]
    fn strip_inline_basic() {
        assert_eq!(
            strip_inline("**bold** and *it* and `code`"),
            "bold and it and code"
        );
    }

    #[test]
    fn strip_inline_link() {
        assert_eq!(
            strip_inline("[link text](https://x.com) rest"),
            "link text rest"
        );
    }

    #[test]
    fn plain_snippet_skips_headings_and_fences() {
        let body = "# Head\n\n```rust\nfn main() {}\n```\n\nReal text here\n\n- item one\n";
        let s = plain_snippet(body, 100);
        assert!(s.contains("Real text here"));
        assert!(s.contains("item one"));
        assert!(!s.contains("fn main"));
        assert!(!s.contains("Head"));
    }

    #[test]
    fn sanitize_filename_removes_invalid() {
        assert_eq!(sanitize_filename("a/b\\c:d?e*f"), "abcdef");
        assert_eq!(sanitize_filename("..."), "untitled");
        assert_eq!(sanitize_filename(""), "untitled");
        assert_eq!(sanitize_filename("my note"), "my note");
    }

    #[cfg(windows)]
    #[test]
    fn repro_read_meta_after_canonicalize() {
        // Regression: `fs::canonicalize` on Windows returns `\\?\`-prefixed
        // paths, which used to make `strip_prefix(root)` fail after save —
        // surfacing as "failed to read note back" toasts after every save.
        let dir = r"D:\GitHub\rustmd\examples";
        let rel = "markdown_render_test.md";
        if !Path::new(&format!("{dir}\\{rel}")).exists() {
            return; // sample notes not checked out
        }
        let root = Path::new(dir);
        let full = resolve_in_root(root, rel).expect("resolve_in_root");
        assert!(
            !full.to_string_lossy().starts_with(r"\\?\"),
            "resolve_in_root must strip the \\?\\ prefix, got {full:?}"
        );
        let meta = read_meta(Path::new(rel), &full).expect("read_meta after save");
        assert_eq!(meta.path, rel);
    }

    #[test]
    fn save_note_impl_skips_write_when_content_identical() {
        let dir = std::env::temp_dir().join("rustmd_test_save_noop");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let args = SaveNoteArgs {
            tags: vec!["a".into()],
            body: "hello\n".into(),
        };
        let meta = save_note_impl(&dir, "note.md", &args.tags, &args.body).unwrap();
        assert_eq!(meta.path, "note.md");
        let mtime_before = fs::metadata(dir.join("note.md"))
            .unwrap()
            .modified()
            .unwrap();
        // Wait longer than the filesystem mtime resolution, then save the
        // identical content again: the file must NOT be rewritten.
        std::thread::sleep(std::time::Duration::from_millis(200));
        save_note_impl(&dir, "note.md", &args.tags, &args.body).unwrap();
        let mtime_after = fs::metadata(dir.join("note.md"))
            .unwrap()
            .modified()
            .unwrap();
        assert_eq!(
            mtime_before, mtime_after,
            "identical content must not rewrite the file"
        );
        // Different content still writes.
        let changed = SaveNoteArgs {
            tags: vec!["a".into()],
            body: "changed\n".into(),
        };
        save_note_impl(&dir, "note.md", &changed.tags, &changed.body).unwrap();
        let mtime_changed = fs::metadata(dir.join("note.md"))
            .unwrap()
            .modified()
            .unwrap();
        assert_ne!(mtime_before, mtime_changed, "changed content must be written");
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn resolve_in_root_rejects_escape() {
        let dir = std::env::temp_dir().join("rustmd_test_root_xyz");
        fs::create_dir_all(&dir).unwrap();
        assert!(resolve_in_root(&dir, "../outside.md").is_err());
        assert!(resolve_in_root(&dir, "..\\..\\win.md").is_err());
        assert!(resolve_in_root(&dir, "C:\\evil.md").is_err());
        let ok = resolve_in_root(&dir, "sub/note.md").unwrap();
        assert!(ok.starts_with(&dir));
        // Existing paths come back canonicalized (junctions resolved), so
        // compare against a canonicalized root.
        let ok_dot = resolve_in_root(&dir, ".").unwrap();
        // `resolve_in_root` strips the `\\?\` prefix, so compare against a
        // canonicalized root with the same stripping applied.
        let canon_dir = strip_extended_prefix(&fs::canonicalize(&dir).unwrap());
        assert!(ok_dot.starts_with(&canon_dir));
        fs::remove_dir_all(&dir).ok();
    }
}
